# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('word', models.TextField(blank=True, null=True)),
                ('explain', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Translate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('word', models.TextField(blank=True, null=True)),
                ('explain', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Words',
                'managed': False,
            },
        ),
    ]
