# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True)),
                ('explain', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Translate',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField(blank=True)),
                ('explain', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Words',
            },
        ),
    ]
